config/routes.rb
Rails.application.routes.draw do
  devise_for :add_confirmable_to_users
  devise_for :admins
  devise_for :users
  resources :categories

  resources :items do
    collection {post :import}
  end
  resources :users 
  root to: 'items#index'

end

app/models/add_confirmable_to_user.rb
class AddConfirmableToUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
	validates :code, :presence => true, :uniqueness => true
	validates :description, :presence => true 
	has_attached_file :uploaded_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/notfound.png"
	validates_attachment_content_type :uploaded_file, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def self.search(keyword)
		if keyword.present?
			where('description like ?', "%#{keyword}%")
		else
			all
		end
	end

	def self.filter(category_id)
		if category_id.present?
			where('category_id = ?', category_id)
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Item.create!(row.to_hash)
		end
	end

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:descr)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if params[:keyword].present? 
      @items = Item.search(params[:keyword]).paginate(:page => params[:page], :per_page => 5)
    elsif params[:category_id].present?
      @items = Item.filter(params[:category_id]).paginate(:page => params[:page], :per_page => 5) 
    else
      @items = Item.paginate(:page => params[:page], :per_page => 5)
    end

    @export_items = Item.all
    #respond_with(@items)
    respond_to do |format|
      format.html
      format.csv {send_data @export_items.to_csv}
      format.xls
    end
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  def import
    Item.import(params[:file])
    redirect_to root_url, notice: "Products imported." 
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:code, :description, :price, :uploaded_file, :category_id)
    end

    def filtering_params(params)
      params.slice(:keyword, :searchdescr, :searchcateg)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:destroy]
	respond_to :html

	def index
		@users = User.all
		respond_with(@users)
	end

	def destroy
	  @user.destroy
      respond_with(@user)
	end

	private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descr %><br>
    <%= f.text_field :descr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<% @categories.each do |category| %>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading<%= category.id %>">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= category.id %>" aria-expanded="false" aria-controls="collapse<%= category.id %>">
          <%= category.descr %>
        </a>
      </h4>
    </div>
    <div id="collapse<%= category.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%= category.id %>">
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Code</th>
              <th>Description</th>
              <th>Price</th>
            </tr>
          </thead>

          <tbody>
            <% category.items.each do |item| %>
              <tr>
                <td class="col-md-2"><%= link_to item.code, item %></td>
                <td class="col-md-5"><%= link_to item.description, item %></td>
                <td class="col-md-1"><%= item.price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>        
      </div>
    </div>
  </div>
  </div>
<% end %>
<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descr:</strong>
  <%= @category.descr %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :uploaded_file %><br>
    <%= f.file_field :uploaded_file %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :descr) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!-- <h1>Listing items</h1> -->
<!-- <form method="get">
 <legend>Search</legend>
 <input type = 'text' class='form-control' value='<%= params[:keyword] %>' name='keyword' placeholder='Keyword'>
</form></br> -->
<% if current_user.admin? %>
  <p>
    Download: 
    <%= link_to "CSV", items_path(format: "csv") %> |
    <%= link_to "Excel", items_path(format: "xls") %>
  </p>
<% end %>
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="1"></th>
      <th>Code</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag item.uploaded_file.url(:thumb), size: "100x100", :class => 'img-circle' %></td>
        <td class="col-md-2"><%= link_to item.code, item %></td>
        <td class="col-md-5"><%= link_to item.description, item %></td>
        <td class="col-md-1"><%= item.price %></td>
        <td class="col-md-2"><%= link_to item.category.descr, items_path(category_id: item.category_id), :class=>'btn btn-success btn-sm',  :role=>"button" if item.category_id.present? %></td>
        <!--<td><%= link_to 'Show', item, :class => 'btn btn-primary' %></td> -->
        <td class="col-md-1"><%= link_to 'Edit', edit_item_path(item), :class => 'btn btn-primary', :role=>"button" if current_user.admin? %></td> 
        <td class="col-md-1"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger', :role=>"button" if current_user.admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.admin %>
  <%= form_tag import_items_path, multipart: true do %>
    <%= file_field_tag :file %></br>
    <%= submit_tag "Import" %>
  <% end %>
<% end %>
<br>
<%= will_paginate @items, :style => 'color:blue' %>
<br>
<% if current_user.admin? %>
  <%= link_to new_item_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New Item
  <% end %>
<% end %>
</br>
</br>
</br>
</br>

app/views/items/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Code</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
        <Cell><Data ss:Type="String">Category</Data></Cell>
      </Row>
    <% @export_items.each do |item| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= item.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.description %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= item.price %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.category.descr %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<p>
<%= image_tag @item.uploaded_file.url(:medium), :class => 'img-rounded' %>
</p>

<%  if @item.category_id.present? %>
<p>
	<strong>Category:</strong>
	<%= @item.category.descr%>
</p>
<% end %>

<p>
  <strong>Code:</strong>
  <%= @item.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Shop</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Items', items_path %></li>
        <% if current_user && current_user.admin? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tables <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Categories', categories_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li class="divider"></li>
            <li><a href="#">Baskets</a></li>
          </ul>
        </li>
        <% end %>
      </ul>
        <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <p class="navbar-text">Logged in as <strong><%= current_user.email %></strong>.</p>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
        </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <legend>Αναζήτηση</legend>
      <%= form_tag items_path, :method => 'get' do %>
        <%= text_field_tag :keyword, params[:keyword], {:class => 'form-control', :placeholder => 'Κωδικός'} %></br>
        <%= text_field_tag :searchdescr, params[:searchdescr], {class: 'form-control', placeholder: 'Περιγραφή'} %></br>
        <%= collection_select :item, params[:searchcateg], Category.all, :id, :descr, {}, {class: 'form-control'} %></br>
        <%= submit_tag "Αναζήτηση", name: "Search" %>
      <% end %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>